Improve lookup form performance on page load
cognitoforms/model.js pull request #45
Opened 2021-01-25 19:54 UTC by pkellz

Description of **Bug 18635**:
"A customer on Zendesk had noticed considerable delay before their public form can be interacted with on load. We have noticed anywhere from a ~4s-10s delay when reproducing. The form has a lookup field that references a form with > 7000 entries. This, in and of itself, shouldn't be a big issue. But the field also has 9 cascading filters. We believe this combination is the main contributing factor of the slowdown.

It appears the bulk of the time is spent looping through lookup entry index instances when initializing lookups. I think this can be optimized in the framework to eliminate this unnecessary work, which would reduce the delay considerable, if not altogether. This would have to be reproduced and the fix tested to prove that it would actually address the problem. Also, the same issue affects Vue forms, so it should at least be fixed there."

This PR reduces the time looping over indexes in `property-chain.js` by only attempting to loop over a `rootType.known()` if the `priorProp` is not null.

After running several performance profiles both with the fix and without the fix, I found average page load times for both categories and it turns out that the changes improved performance by ~3 seconds (4300 entries x 9 cascading filters)

**_Page load times without changes_**
~12150 ms
~11970 ms
~13983 ms
~14115 ms
**Average without changes: ~13 seconds**

**_Page load times with changes_**
~13400 ms
~9200 ms
~8980 ms
~8720 ms
**Average with changes: ~10 seconds**

2021-01-29 20:34 UTC, tskimmett requested changes
It would be nice to see some (unit) testing which emulates the scenario. It sounds like the test would assert whether we are making superfluous calls to `PropertyChain.testConnection()`. The most valuable part of the test would probably be seeing a simple reproduction of the model setup which exposes the issue.

My current understanding of this change is that it's a slight optimization for changes to the first property in a property chain, since we won't unnecessarily loop over pooled entities to see if they are linked to the changed entity via a `null` property, because `testConnection` would only return `true` if they are the same entity.

2021-02-01 13:56 UTC, pkellz commented
I'll look into creating the appropriate unit tests. 

And yes, you're understanding sounds correct. @mattheyan Can you confirm?

2021-02-03 13:30 UTC, mattheyan commented
Yes, it is an optimization, and that description is accurate. It was an oversight in the implementation that's lingered for years. I would say its a slight optimization in most cases (as evidenced by the fact that its lingered this long), but it depends on the scenario. In the case of a lookup with lots of entries, the impact is pretty significant (at least it definitely was in legacy). Patrick, do you remember if the same noticeable delay occurred in Vue forms as well. I seem to remember you confirmed the problem by measurement, but just curious if it was also noticeable to the user.

2021-02-03 20:16 UTC, pkellz commented
I believe I had noticed the Vue delay but it didn't feel outrageous. Overall, Vue was still noticeably quicker than legacy.

2021-03-01 15:21 UTC, tskimmett approved these changes

2021-03-01 15:29 UTC, merged