Prevent caching of resources by wrapping them in functions
cognitoforms/model.js pull request #48
Opened 2021-02-18 16:53 UTC by Christopher-Masselli

Prevent resources from being cached so that resource changes after initialization are used.

2021-02-18 21:06 UTC, tskimmett requested changes
Changes look good ✔️ 
Can we take this time to add some basic tests for these rule types? Doesn't have to be anything too crazy. `string-length-rule` looks pretty much like what I'm thinking.

2021-02-19 19:57 UTC, Christopher-Masselli commented
@tskimmett I added rule tests for each rule, while doing the required rule I found an issue with the new wrapping of resource so there is an extra change in `required-rule.ts` on line 46 to set the default `options.isValid` even if `options.message` is a function

2021-02-19 22:52 UTC, tskimmett requested changes

2021-02-19 22:52 UTC, tskimmett commented
I pushed a couple more required rule tests to cover more variations of property required options.

2021-02-22 13:52 UTC, Christopher-Masselli commented on src/calculated-property-rule.unit.ts
> -				Choice_Choices: {
They weren't needed, since the function in allowedValues is where we get the allowed values from.

2021-02-22 13:54 UTC, Christopher-Masselli commented on src/condition-rule.unit.ts
> +		let consoleOutputs = [];
Removed.

2021-02-22 13:59 UTC, tskimmett approved these changes

2021-02-22 14:26 UTC, merged